---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudprovider-secret-controller
rules:

# New Rules added to ClusterInstaller
# Leader Lock requires configmaps(create&get) and pods(get)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","update"]

# Leader election
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch