apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: provider-credential-controller
  name: provider-credential-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: provider-credential-controller
  template:
    metadata:
      labels:
        name: provider-credential-controller
    spec:
      containers:
      - command:
        - "./manager"
        - "-enable-leader-election"
        image: quay.io/jpacker/provider-credential-controller:0.1
        imagePullPolicy: Always
        name: provider-credential-controller
        resources:
          limits:
            cpu: "20m"
            memory: "500Mi"
          requests:
            cpu: "3m"
            memory: "65Mi"
      serviceAccountName: provider-credential-controller
